apiVersion: v1
kind: ServiceAccount
metadata:
  name: managed-velero-operator
  namespace: openshift-velero
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
