apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: openshift-velero
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
