apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  value: staging
  required: true
- name: IMAGE_TAG
  required: true
- name: REPO_NAME
  value: managed-velero-operator
  required: true

objects:
- apiVersion: hive.openshift.io/v1alpha1
  kind: SelectorSyncSet
  metadata:
    name: managed-velero-operator
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
    resourceApplyMode: sync
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-velero
        annotations:
          openshift.io/node-selector: ''
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        labels:
          opsrc-datastore: 'true'
          opsrc-provider: redhat
        name: managed-velero-operator-registry
        namespace: openshift-velero
      spec:
        image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
        displayName: Managed Velero Operator
        icon:
          base64data: ''
          mediatype: ''
        publisher: Red Hat
        sourceType: grpc
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: managed-velero-operator
        namespace: openshift-velero
      spec:
        channel: ${CHANNEL}
        name: managed-velero-operator
        source: managed-velero-operator-registry
        sourceNamespace: openshift-velero
    - apiVersion: operators.coreos.com/v1alpha2
      kind: OperatorGroup
      metadata:
        name: managed-velero-operator
        namespace: openshift-velero
      spec:
        targetNamespaces:
        - openshift-velero
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: managed-velero-operator-cluster-config-v1-reader
        namespace: kube-system
        labels:
          owner: managed-velero-operator
          owner.namespace: managed-velero-operator
      subjects:
      - kind: ServiceAccount
        name: managed-velero-operator
        namespace: openshift-velero
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: cluster-config-v1-reader
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        creationTimestamp: null
        name: cluster-config-v1-reader
        namespace: kube-system
      rules:
      - apiGroups:
        - ""
        resourceNames:
        - cluster-config-v1
        resources:
        - configmaps
        verbs:
        - get
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: managed-velero-operator
        namespace: openshift-velero
      subjects:
      - kind: ServiceAccount
        name: managed-velero-operator
        namespace: openshift-velero
      roleRef:
        kind: ClusterRole
        name: managed-velero-operator
        apiGroup: rbac.authorization.k8s.io
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        creationTimestamp: null
        name: managed-velero-operator
        namespace: openshift-velero
      rules:
      - apiGroups:
        - apiextensions.k8s.io
        resources:
        - customresourcedefinitions
        verbs:
        - '*'
      - apiGroups:
        - config.openshift.io
        resources:
        - infrastructures
        verbs:
        - get
        - list
        - watch
    - apiVersion: cloudcredential.openshift.io/v1
      kind: CredentialsRequest
      metadata:
        name: managed-velero-operator-iam-credentials
        namespace: openshift-velero
      spec:
        secretRef:
          name: managed-velero-operator-iam-credentials
          namespace: openshift-velero
        providerSpec:
          apiVersion: cloudcredential.openshift.io/v1
          kind: AWSProviderSpec
          statementEntries:
          - effect: Allow
            action:
            - s3:CreateBucket
            - s3:ListBucket
            - s3:PutBucketAcl
            - s3:PutBucketPublicAccessBlock
            - s3:PutEncryptionConfiguration
            - s3:PutLifecycleConfiguration
            resource: "*"
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: managed-velero-operator
        namespace: openshift-velero
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: managed-velero-operator
        template:
          metadata:
            labels:
              name: managed-velero-operator
          spec:
            serviceAccountName: managed-velero-operator
            containers:
              - name: managed-velero-operator
                image: quay.io/openshift-sre/managed-velero-operator
                command:
                - managed-velero-operator
                imagePullPolicy: Always
                env:
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: OPERATOR_NAME
                    value: "managed-velero-operator"
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: prometheus-k8s
        namespace: openshift-velero
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: prometheus-k8s
      subjects:
      - kind: ServiceAccount
        name: prometheus-k8s
        namespace: openshift-monitoring
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: prometheus-k8s
        namespace: openshift-velero
      rules:
      - apiGroups:
        - ""
        resources:
        - services
        - endpoints
        - pods
        verbs:
        - get
        - list
        - watch
      kind: RoleBinding
    - apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: managed-velero-operator
        namespace: openshift-velero
      subjects:
      - kind: ServiceAccount
        name: managed-velero-operator
        namespace: openshift-velero
      roleRef:
        kind: Role
        name: managed-velero-operator
        apiGroup: rbac.authorization.k8s.io
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        creationTimestamp: null
        name: managed-velero-operator
        namespace: openshift-velero
      rules:
      - apiGroups:
        - ""
        resources:
        - pods
        - services
        - services/finalizers
        - endpoints
        - persistentvolumeclaims
        - events
        - configmaps
        - secrets
        verbs:
        - '*'
      - apiGroups:
        - apps
        resources:
        - deployments
        - daemonsets
        - replicasets
        - statefulsets
        verbs:
        - '*'
      - apiGroups:
        - monitoring.coreos.com
        resources:
        - servicemonitors
        verbs:
        - get
        - create
      - apiGroups:
        - apps
        resourceNames:
        - managed-velero-operator
        resources:
        - deployments/finalizers
        verbs:
        - update
      - apiGroups:
        - ""
        resources:
        - pods
        verbs:
        - get
      - apiGroups:
        - apps
        resources:
        - replicasets
        verbs:
        - get
      - apiGroups:
        - managed.openshift.io
        resources:
        - veleros
        - veleros/status
        - veleros/finalizers
        verbs:
        - '*'
      - apiGroups:
        - velero.io
        resources:
        - '*'
        verbs:
        - '*'
      - apiGroups:
        - cloudcredential.openshift.io
        resources:
        - credentialsrequests
        verbs:
        - '*'
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: managed-velero-operator
        namespace: openshift-velero
      kind: ClusterRoleBinding
    - apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: velero
      subjects:
      - kind: ServiceAccount
        name: velero
        namespace: openshift-velero
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: velero
        namespace: openshift-velero
