apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: veleroinstalls.managed.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.storageBucket.name
    description: Name of the storage bucket
    name: Bucket
    type: string
  - JSONPath: .status.storageBucket.provisioned
    description: Has the storage bucket been successfully provisioned
    name: Provisioned
    type: boolean
  - JSONPath: .status.storageBucket.lastSyncTimestamp
    name: Last Sync
    type: date
  group: managed.openshift.io
  names:
    kind: VeleroInstall
    listKind: VeleroInstallList
    plural: veleroinstalls
    singular: veleroinstall
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: VeleroInstall is the Schema for the veleroinstalls API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VeleroInstallSpec defines the desired state of Velero
          type: object
        status:
          description: VeleroInstallStatus defines the observed state of Velero
          properties:
            AWS:
              description: AWSVeleroInstallStatus contains status information specific
                to AWS
              properties:
                storageBucket:
                  description: StorageBucket contains details of the storage bucket
                    for backups on AWS
                  properties:
                    lastSyncTimestamp:
                      description: LastSyncTimestamp is the time that the bucket policy
                        was last synced.
                      format: date-time
                      type: string
                    name:
                      description: Name is the name of the storage bucket created
                        to store Velero backup details
                      maxLength: 63
                      type: string
                    provisioned:
                      description: Provisioned is true once the bucket has been initially
                        provisioned.
                      type: boolean
                  required:
                  - provisioned
                  type: object
              type: object
            Azure:
              description: AWSVeleroInstallStatus contains status information specific
                to Azure
              properties:
                storageAccount:
                  description: StorageAccount contains details of the storage account
                    for backups on Azure
                  type: string
                storageBucket:
                  description: StorageBucket contains details of the storage bucket
                    for backups on Azure
                  properties:
                    lastSyncTimestamp:
                      description: LastSyncTimestamp is the time that the bucket policy
                        was last synced.
                      format: date-time
                      type: string
                    name:
                      description: Name is the name of the storage bucket created
                        to store Velero backup details
                      maxLength: 63
                      type: string
                    provisioned:
                      description: Provisioned is true once the bucket has been initially
                        provisioned.
                      type: boolean
                  required:
                  - provisioned
                  type: object
              type: object
            GCP:
              description: AWSVeleroInstallStatus contains status information specific
                to GCP
              properties:
                storageBucket:
                  description: StorageBucket contains details of the storage bucket
                    for backups on GCP
                  properties:
                    lastSyncTimestamp:
                      description: LastSyncTimestamp is the time that the bucket policy
                        was last synced.
                      format: date-time
                      type: string
                    name:
                      description: Name is the name of the storage bucket created
                        to store Velero backup details
                      maxLength: 63
                      type: string
                    provisioned:
                      description: Provisioned is true once the bucket has been initially
                        provisioned.
                      type: boolean
                  required:
                  - provisioned
                  type: object
              type: object
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
