// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVeleroInstallStatus) DeepCopyInto(out *AWSVeleroInstallStatus) {
	*out = *in
	in.StorageBucket.DeepCopyInto(&out.StorageBucket)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVeleroInstallStatus.
func (in *AWSVeleroInstallStatus) DeepCopy() *AWSVeleroInstallStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVeleroInstallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVeleroInstallStatus) DeepCopyInto(out *AzureVeleroInstallStatus) {
	*out = *in
	if in.StorageAccount != nil {
		in, out := &in.StorageAccount, &out.StorageAccount
		*out = new(string)
		**out = **in
	}
	in.StorageBucket.DeepCopyInto(&out.StorageBucket)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVeleroInstallStatus.
func (in *AzureVeleroInstallStatus) DeepCopy() *AzureVeleroInstallStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVeleroInstallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVeleroInstallStatus) DeepCopyInto(out *GCPVeleroInstallStatus) {
	*out = *in
	in.StorageBucket.DeepCopyInto(&out.StorageBucket)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVeleroInstallStatus.
func (in *GCPVeleroInstallStatus) DeepCopy() *GCPVeleroInstallStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVeleroInstallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBucket) DeepCopyInto(out *StorageBucket) {
	*out = *in
	if in.LastSyncTimestamp != nil {
		in, out := &in.LastSyncTimestamp, &out.LastSyncTimestamp
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBucket.
func (in *StorageBucket) DeepCopy() *StorageBucket {
	if in == nil {
		return nil
	}
	out := new(StorageBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstall) DeepCopyInto(out *VeleroInstall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstall.
func (in *VeleroInstall) DeepCopy() *VeleroInstall {
	if in == nil {
		return nil
	}
	out := new(VeleroInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VeleroInstall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstallList) DeepCopyInto(out *VeleroInstallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VeleroInstall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstallList.
func (in *VeleroInstallList) DeepCopy() *VeleroInstallList {
	if in == nil {
		return nil
	}
	out := new(VeleroInstallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VeleroInstallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstallSpec) DeepCopyInto(out *VeleroInstallSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstallSpec.
func (in *VeleroInstallSpec) DeepCopy() *VeleroInstallSpec {
	if in == nil {
		return nil
	}
	out := new(VeleroInstallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstallStatus) DeepCopyInto(out *VeleroInstallStatus) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSVeleroInstallStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPVeleroInstallStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureVeleroInstallStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstallStatus.
func (in *VeleroInstallStatus) DeepCopy() *VeleroInstallStatus {
	if in == nil {
		return nil
	}
	out := new(VeleroInstallStatus)
	in.DeepCopyInto(out)
	return out
}
