apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: managed-velero-operator-iam-credentials-azure
  namespace: openshift-velero
spec:
  secretRef:
    name: managed-velero-operator-iam-credentials
    namespace: openshift-velero
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
    - Contributor