apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: managed-velero-operator.v0.0.1
  namespace: placeholder
  annotations:
    certified: "false"
    description: Operator to manage installation of Velero in OpenShift.
    containerImage: quay.io/app-sre/managed-velero-operator:latest
    createdAt: "2019-11-11T11:00:00Z"
    support: Christoph Blecker
    alm-examples: '[{"apiVersion":"managed.openshift.io/v1alpha1","kind":"Velero","metadata":{"name":"cluster","namespace":"openshift-velero"}}]'
spec:
  displayName: Managed Velero Operator
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Velero
      name: veleros.managed.openshift.io
      version: v1alpha1
  description: Operator to manage installation of Velero in OpenShift.
  keywords:
  - kubernetes
  - backup
  - openshift
  - velero
  - storage
  version: 0.0.1
  provider:
    name: Red Hat, Inc
  maturity: alpha
  displayName: Managed Velero Operator
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: managed-velero-operator
        # Rules will be added here by the generate-csv.py script.
      deployments:
      - name: managed-velero-operator
      # Deployment spec will be added here by the generate-csv.py script.
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - managed-velero-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - managed.openshift.io
          resources:
          - veleros
          - veleros/status
          - veleros/finalizers
          verbs:
          - '*'
        - apiGroups:
          - velero.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - cloudcredential.openshift.io
          resources:
          - credentialsrequests
          verbs:
          - '*'
        serviceAccountName: managed-velero-operator
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
