//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBucket) DeepCopyInto(out *StorageBucket) {
	*out = *in
	if in.LastSyncTimestamp != nil {
		in, out := &in.LastSyncTimestamp, &out.LastSyncTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBucket.
func (in *StorageBucket) DeepCopy() *StorageBucket {
	if in == nil {
		return nil
	}
	out := new(StorageBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstall) DeepCopyInto(out *VeleroInstall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstall.
func (in *VeleroInstall) DeepCopy() *VeleroInstall {
	if in == nil {
		return nil
	}
	out := new(VeleroInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VeleroInstall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstallList) DeepCopyInto(out *VeleroInstallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VeleroInstall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstallList.
func (in *VeleroInstallList) DeepCopy() *VeleroInstallList {
	if in == nil {
		return nil
	}
	out := new(VeleroInstallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VeleroInstallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstallSpec) DeepCopyInto(out *VeleroInstallSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstallSpec.
func (in *VeleroInstallSpec) DeepCopy() *VeleroInstallSpec {
	if in == nil {
		return nil
	}
	out := new(VeleroInstallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstallStatus) DeepCopyInto(out *VeleroInstallStatus) {
	*out = *in
	in.StorageBucket.DeepCopyInto(&out.StorageBucket)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstallStatus.
func (in *VeleroInstallStatus) DeepCopy() *VeleroInstallStatus {
	if in == nil {
		return nil
	}
	out := new(VeleroInstallStatus)
	in.DeepCopyInto(out)
	return out
}
